### ISSUE TITLE
The problem with JAVA_HOME

### ISSUE THREAD

**Issue by otrosien** [ePages-de/mac-dev-setup#11]
.. can be solved by providing a symlink, e.g. 

```bash
cd /Library/Java/JavaVirtualMachines
ln -s jdk1.8.0_121.jdk latest
```

Then, you never need to update $JAVA_HOME anymore, just point to latest, and move the symlink from time to time.

**Comment by otrosien** [comment]
if interested, this seems to do the trick AFAICS:

https://github.com/otrosien/mac-dev-setup/commit/352ce39eb37c4be1f7d4d69247984400efe1bc2d

**Comment by jensfischer1515** [comment]
So the benefit is not in never touching `.bash_profile.j2` anymore, but to keep `launchd.conf.j2` stable? Sounds interesting, especially after touching that file again today due to JDK upgrade.
